navikt/veilarbmaofs

- src/app/utils/datafetcher.tsx
> [KAIZEN-0] legger til alertstripe ved feil i lasting av data

- src/app/datatyper/arenaperson.ts
- src/app/visningskomponenter/cv/cv.tsx
- src/app/visningskomponenter/cv/forerkort.tsx
- src/app/visningskomponenter/cv/kurs.tsx
- src/app/visningskomponenter/cv/sertifikater.tsx
- src/app/visningskomponenter/cv/sprak.tsx
- src/mock/cv.ts
Tilpasninger etter endringer i API-et til PAM
> Nytt cv api

- package-lock.json
- package.json
- src/app/basisinfo/apne-lukke-knapp.tsx
- src/app/basisinfo/basisinfo-visning.tsx
- src/app/basisinfo/basisinfo.less
- src/app/basisinfo/basisinfo.tsx
- src/app/basisinfo/etiketter.less
- src/app/basisinfo/etiketter.tsx
- src/app/basisinfo/placeholder.tsx
- src/app/visningskomponenter/personalia/barn.tsx
- src/mock/personalia.ts
Legger til etiketter og visning av død.
Retter også at vi ikke lenger viser overskriften `Barn under 21 år` hvis det ikke finnes noen barn.
> Fo 1209 etiketter

- public/index.html
- src/app/application.tsx
- src/app/persondetaljer.tsx
- src/app/tilbakelenke.tsx
- src/app/visningskomponenter/oppfolging/oppfolging.tsx
Mao kan også få inn en enhet for tilbake linken
> KAIZEN-0: enheter kan mangle

- src/app/utils/float-grid.tsx
- src/app/utils/util.ts
- src/app/visningskomponenter/cv/beskrivelse.tsx
- src/app/visningskomponenter/cv/cv.tsx
- src/app/visningskomponenter/cv/forerkort.tsx
- src/app/visningskomponenter/cv/kompetanse.tsx
- src/app/visningskomponenter/cv/kurs.tsx
- src/app/visningskomponenter/cv/sertifikater.tsx
- src/app/visningskomponenter/cv/sprak.tsx
- src/app/visningskomponenter/cv/utdanning.tsx
- src/app/visningskomponenter/cv/verv.tsx
- src/app/visningskomponenter/cv/yrkeserfaring.tsx
- src/app/visningskomponenter/felles-komponenter/informasjonsbolk.tsx
Designet av meg, godkjent av prod.eier. ;)
> [KAIZEN-0] Forbedringer til CV

- src/app/datatyper/registreringsData.ts
- src/app/visningskomponenter/registrering/profilering.tsx
- src/app/visningskomponenter/registrering/registrering.tsx
- src/app/visningskomponenter/registrering/registrert-tid.tsx
- src/app/visningskomponenter/registrering/registrert.tsx
- src/app/visningskomponenter/registrering/sporsmolvisning.tsx
- src/config.ts
- src/mock/standard/registrering.ts
lagt til profileringsdata i registrering og
endret til å virke med nytt endepunkt
> [FO-1447] lagt til profileringsdata i registrering

- src/app/visningskomponenter/visningsbolk.tsx
- src/fetch-cache.ts
> FO-1482: Track time properly

- src/components/paneler/innhold/oppfolging/oppfolging-panel-innhold.tsx
- src/components/paneler/innhold/ytelser/innsatsgruppe.tsx
- src/components/paneler/innhold/ytelser/ytelser-panel-innhold.tsx
- src/rest/datatyper/oppfolgingsstatus.ts
- src/rest/datatyper/ytelse.ts
- src/utils/arena-status-utils.ts
Ny kilde gir kodeverdier som må mappes om til tekst
> FO-3016 endre kilde for servicegruppe

- src/components/paneler/innhold/cv/cv-panel-innhold.tsx
- src/components/paneler/innhold/jobbprofil/jobbprofil-panel-innhold.tsx
- src/utils/index.ts
Oppdaterer URLene til å peke på den nye løsningen på `https://pam-personbruker-veileder...`
> Endre url for CV-registrering

- src/components/paneler/innhold/jobbprofil/jobbprofil-panel-innhold.tsx
Gjør det enklere for veilederne å kommunisere med brukere av Arbeidsplassens løsning
> Endre jobbprofil-overskrifter til Arbeidsplassens

- src/app.tsx
Sendes ingenting herfra lenger: [veilarbvisittkortfs/pull/200](https://github.com/navikt/veilarbvisittkortfs/pull/200)
> Fjern kode som ikke trigges av visittkort lenger

- CODEOWNERS
- src/components/felles/kopiknapp.less
- src/components/felles/kopiknapp.tsx
- src/components/sidemeny/sidemeny.less
- src/components/sidemeny/sidemeny.tsx
- aria-label og tooltip på kopiknapper
- mer beskrivende navigasjonsregion på sidemeny
> Fikser UU-mangler etter brukertest

- src/utils/index.ts
Endringsønske FAGSYSTEM-239759
> Tc-258 Formater alle telefonnumre som xxx xx xxx

- src/components/paneler/innhold/registrering/registrering-panel-innhold.tsx
Viser feilmeldingstekst når det ikke finnes en registrering
> Legg til feilmelding når registrering mangler

- nais-dev.yaml
- nais-prod.yaml
Ref: https://nav-it.slack.com/archives/CQ2H1AY3Z/p1673598233489549
> TC-272 Legg til nais yaml filer igjen

- .github/workflows/poao-frontend-container-dev.yaml
- .github/workflows/poao-frontend-container-prod.yaml
`NAIS_DEPLOY_APIKEY` er riktig navn for dette repoet, ref: https://github.com/navikt/veilarbmaofs/settings/secrets/actions
> Bruke riktig secret-navn for deployment api-nøkkel

- .github/workflows/deploy-dev-gcp.yaml
Ref: https://nav-it.slack.com/archives/CQ2H1AY3Z/p1678192756945219?thread_ts=1678095853.805939&cid=CQ2H1AY3Z
> Bruke ny ingress ved bygging

- .nais/obo-nais-dev.yaml
Ref: https://nav-it.slack.com/archives/CQ2H1AY3Z/p1678198147308709?thread_ts=1678095853.805939&cid=CQ2H1AY3Z
> Fikse CORS-feil etter endring av dev-ingress

- .github/workflows/deploy-prod-gcp.yaml
- .github/workflows/update-github-pages.yaml
- package-lock.json
- package.json
- src/components/paneler/innhold/cv/annen-erfaring.tsx
- src/components/paneler/innhold/cv/arbeidserfaring.tsx
Relatert til endringer hos Arbeidsplassen: https://jira.adeo.no/browse/FAGSYSTEM-255228
> FS-255228: Oppdater CV-titler + pakkebumping

- .nais/obo-nais-dev.yaml
> Fjerner veilarbmaofs i dev
